name: pr-regression-tests-on-comment

on:
  issue_comment:
    types: [created]

jobs:
  pr_regression_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          # cache: "yarn"
          node-version-file: ".nvmrc"

      - name: Run regression-tests
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/regression-tests') && !contains(github.event.comment.body, '--base-url') }}
        run: |
          echo "corri sem base-url"
          exit 1

      - name: Run regression-tests against TBDFE
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/regression-tests --base-url=') }}
        env:
          BASE_URL: ${{ github.event.comment.body }}
        id: split
        run: |
          echo "fragment=${BASE_URL##*=}" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
          echo "corri com base-url"