name: pr-regression-tests-on-comment

on:
  issue_comment:
    types: [created]

jobs:
  pr_regression_tests:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/regression-tests' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          # cache: "yarn"
          node-version-file: ".nvmrc"

      - name: Run regression-tests
        if: "!contains(github.event.comment.body, '--base-url')"
        run: |
          npm install -g yarn@1.22.10
          scl enable devtoolset-7 "yarn install"
          cd apps/web
          yarn test:regression:grid:phone
          yarn test:regression:report:generate

      - name: Run regression-tests against TBDFE
        if: contains(github.event.comment.body, '--base-url')
        run: |
          DOCKER_BUILDKIT=1 docker-compose -f apps/web/Docker/tests/docker-compose.yml -f apps/web/Docker/tests/docker-compose.regression.yml up --exit-code-from testexecutor --build
