name: pr-regression-tests-on-comment

on:
  issue_comment:
    types: [created]

jobs:
  pr_regression_tests:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/regression-tests') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
          hub pr checkout $PR_NUM
      - uses: actions/setup-node@v3
        with:
          # cache: "yarn"
          node-version-file: ".nvmrc"

      - name: Run regression-tests
        if: ${{ !contains(github.event.comment.body, '--base-url') }}
        continue-on-error: false
        run: |
          echo "corri sem base-url"
          exit 1

      - name: Run regression-tests against TBDFE
        if: ${{ contains(github.event.comment.body, '--base-url') }}
        continue-on-error: true
        env:
          BASE_URL: ${{ github.event.comment.body }}
        run: |
          echo $BASE_URL
          URL=${BASE_URL##*=}
          echo "test url: $URL"
          echo "corri com base-url"
          exit 1
          
      - name: Output report
        run: |
          echo "Report"