name: pr-regression-tests-on-comment

on:
  issue_comment:
    types: [created]

jobs:
  pr_regression_tests:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/regression-tests') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          # cache: "yarn"
          node-version-file: ".nvmrc"

      - name: Run regression-tests
        id: test
        if: ${{ !contains(github.event.comment.body, '--base-url') }}
        run: |
          echo "corri sem base-url"
          exit 1

      - name: Run regression-tests against TBDFE
        if: ${{ contains(github.event.comment.body, '--base-url') }}
        env:
          BASE_URL: ${{ github.event.comment.body }}
        run: |
          echo $BASE_URL
          URL=${BASE_URL##*=}
          echo "test url: $URL"
          echo "corri com base-url"
          
      - name: Output report
        if: ${{ steps.test.outputs.result == success() }}
        run: |
          echo "Report"