name: pr-regression-tests-on-comment

on:
  issue_comment:
    types: [created]

jobs:
  pr_regression_tests:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/regression-tests') }}
    runs-on: ubuntu-latest
    steps:
      - name: Github API Request
        id: request
        uses: octokit/request-action@v2.0.2
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{fromJson(steps.request.outputs.data).head.repo.full_name}}
          ref: ${{fromJson(steps.request.outputs.data).head.ref}}
      - uses: actions/setup-node@v3
        with:
          # cache: "yarn"
          node-version-file: ".nvmrc"

      - name: Run regression-tests
        if: ${{ !contains(github.event.comment.body, '--base-url') }}
        continue-on-error: false
        run: |
          echo "corri sem base-url"
          exit 1

      - name: Run regression-tests against TBDFE
        if: ${{ contains(github.event.comment.body, '--base-url') }}
        continue-on-error: true
        env:
          BASE_URL: ${{ github.event.comment.body }}
        run: |
          echo $BASE_URL
          URL=${BASE_URL##*=}
          echo "test url: $URL"
          echo "corri com base-url"
          exit 1
          
      - name: Output report
        run: |
          echo "Report"